version: '3'
services:
  web:
    build: .
    ports:
      - "4000:4000"
    env_file:
      - phx.env
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
       - db_data:/var/lib/postgresql/data
    env_file:
      - psql.env
volumes:
  db_data:
