version: '3'
services:
  web:
    build: .
    ports:
      - "4000:4000"
    environment:
      - MIX_ENV=dev
      - PORT=4000
    volumes:
      - .:/app
    links:
      - db
  db:
    image: postgres
    volumes:
       - db_data:/var/lib/postgresql/data
    environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
       - POSTGRES_HOST=localhost
volumes:
    db_data:
