version: '3'
services:
#  web:
#    build: .
#    ports:
#      - "4000:4000"
#    env_file:
#      - phx.env
#    volumes:
#      - .:/app
#    depends_on:
#      - db
  db:
    image: postgres:9.3.17
    ports:
          - "5432:5432"
    volumes:
       - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=phoenix
      - POSTGRES_DB=phx_app
volumes:
  db_data:
