version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: elixir
      - image: postgres
        environment:
          MIX_ENV: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOSTNAME: localhost
          POSTGRES_DB: postgres
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar
      - run: mix deps.get
      - run: mix ecto.create
      - run: mix test
